#!bin/bash


echo $#
echo $@
for var in $@; do
	case $var in
		"-t1")  cut -d";" -f1,2,11,12,13 meteo_filtered_data_v1.csv | sort -n > temp.txt ;;
		"-t2")  cut -d";" -f1,10 meteo_filtered_data_v1.csv | sort -rn > temp_moy.txt ;; ## a faire
		"-t3") ## à faire
		"-p1")  cut -d";" -f1,2,7 meteo_filtered_data_v1.csv | sort -n > pression.txt ;;
		"-h")  cut -d";" -f1,14 meteo_filtered_data_v1.csv | sort -t";" -k2 -rn > altitude.txt ;;
		"-m")  cut -d";" -f1,6 meteo_filtered_data_v1.csv | sort -t";" -k2 -rn > humidite.txt ;;
	esac 
done
