#!/bin/bash

##   ${!i}  permt de réutiliser la valeur de i comme nom de variable


echo $#
echo $@
for var in $@; do ### for i in $(seq 1 10)
	if [${!i} == $arg0] ; then
		echo 'argument 0'
	fi
done
